[package]
name = "rbmenu"
version = "0.2.0"
authors = ["DevHyperCoder <arduinoleo88@gmail.com>"]
edition = "2018"
description = "Rust Bookmark (d)Menu"
readme = "README.md"
repository = "https://github.com/DevHyperCoder/rbmenu"
license = "GPL-3.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.21"
serde_json = "1.0.64"
serde = {version =  "1.0.0", features = ["derive"]}
regex = "1"
home = "0.5.3"
chrono = "0.4"
substring = "1.4.5"
colored = "2"
